### ISSUE TITLE
Need help getting started

### ISSUE THREAD

**Issue by wayner9** [UAce/gggolfclient#1]
How do I install this?  I just did a git clone and then there seem to be a bunch of prereqs - like credentials_info.  But when I try to do a pip install of credentials_info it says 
ERROR: Could not find a version that satisfies the requirement credentials_info (from versions: none)

Is there a minimum Python version?  Python3.7?

**Comment by UAce** [comment]
Hey @wayner9, check the credentials_template.py file (my bad, I should've written something in the Readme). To be honest, I'm not sure if it still works or not since I haven't properly tested it 😅 (don't have an account anymore) but let me know if you run into any issues.

**Comment by UAce** [comment]
I'll do something about the dependencies later

**Comment by wayner9** [comment]
Thanks - is there any documentation available anywhere?  A lot of the stuff that I would need to use this are constants - like always the same golf course, etc.  Is there some way I can just try to send test HTTP PUTs or GETs to figure out the syntax?  Using an app like Postman or a browser?

**Comment by UAce** [comment]
@wayner9 well you could technically. I'm just making regular requests to the secure gggolf website as if you were on the website and clicking around (but I don't think I use sessions so every actions does a login).

**Comment by UAce** [comment]
@wayner9 i just tried running it, and i don't think it's working anymore. It uses webscraping to get the information so it's most likely outdated by now :(

**Comment by wayner9** [comment]
OK thanks.  I was interested in primarily using it to book tee times at one specific course, a private golf club, rather than to view existing times at various courses.  That would allow me to have an edge in booking desired tee times as I could have a script book a tee time as soon as booking starts.  At my club I can book tee times 7 days in advance for weekdays starting at 6:30am.  It would be nice to set up the process the night before to book a tee time for my preferred time without having to get up early.

**Comment by UAce** [comment]
That was the initial purpose of this project. But since I don't have an account for that private golf club, I can't really test and fix it.

**Comment by wayner9** [comment]
Any advice on software to use to try to capture the HTTP GETs and PUTs that are going between my PC and GGGolf?  There is Wireshark, but that is a very low level capture.  Is there other software that can capture what Chrome is sending in terms of the HTTP requests when you press the "Book" button for a tee time.

**Comment by UAce** [comment]
In Chrome developer tools > network tab, you can see all the requests. Basically, you check the first request that is made when you click a button on the website.

What you'll need first is the login request (a POST request) to get your security token, then I guess use that token in your other requests to make reservations.

You can copy the curl commands and run them in your terminal. If you're not familiar with bash, you can even convert the curl to http requests in Python with postman or similar tools.
